### ISSUE TITLE
Error when Creating Pilet with Vue 3 Template: No Matching Version Found for vue-loader@^18

### ISSUE THREAD

**Issue by paddomanno** [smapiot/piral-templates#1]
# Bug Report

When attempting to create a new Pilet using the provided Vue 3 template in the Piral CLI, I encountered an error related to the vue-loader package. The error message suggests that there is no matching version found for vue-loader@^18, which is required by the template. However, the latest available version of vue-loader is only 17.3.1, and version 18 does not exist.

This is the line from the template in question causing the issue: https://github.com/smapiot/piral-templates/blame/f1f0c4a1e1cdbdf066d018cda4c4a0509c78c53e/templates/pilet-template-vue/src/helpers.ts#L34

## Environment Details and Version

Piral CLI version: 1.3.2
Vue version: 3
Piral template: Vue 3

This project uses the locally run Sample Pilet Feed v1.3.2 ([GitHub](https://github.com/smapiot/sample-pilet-service)).

### Project Configuration

1. Piral Instance `my-app` (app shell)
2. First pilet `my-pilet` (micro-frontend/fragment)
3. Feed service running in memory via `npx sample-pilet-service`

Versions in Pilet called "my-pilet-vue-1":

```
{
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@vue/compiler-sfc": "^3",
    "my-app": "file:..\\my-app\\dist\\emulator\\my-app-1.0.0.tgz",
    "piral-cli": "1.3.2",
    "piral-cli-webpack5": "1.3.3",
    "piral-vue-3": "1.3.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-router": "5.3.4",
    "react-router-dom": "5.3.4",
    "tslib": "2.6.2",
    "typescript": "latest",
    "vue": "^3",
    "vue-loader": "^17.3.1"
  }
}
```

Versions in Piral instance called "my-app":

```
{
  "dependencies": {
    "piral": "1.3.2",
    "piral-base": "1.3.2",
    "piral-core": "1.3.2",
    "react": "^18",
    "react-dom": "^18",
    "react-router": "^5",
    "react-router-dom": "^5"
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/react-router": "^5",
    "@types-react-router-dom": "^5",
    "piral-cli": "1.3.2",
    "piral-cli-webpack5": "1.3.2",
    "typescript": "latest"
  }
}
```

## Steps to Reproduce

`piral new ./my-app/dist/emulator/my-app-1.0.0.tgz --target my-pilet-vue-1 --template vue --vars.standalone true --vars.vueVersion 3
`

## Expected behavior

The Pilet creation process should work without encountering errors related to package versions that do not exist.

## Actual behavior
Console log:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for vue-loader@^18.
npm ERR! notarget In most cases, you or one of your dependencies are requesting a package version that doesn't exist.
```

## Possible Origin / Solution

Workaround:
Manually installing vue-loader version 17.3.1 after using the Piral CLI with the template allows the project to work as expected.

**Comment by FlorianRappl** [comment]
Ok thanks for the info - I have a look at this!

**Comment by FlorianRappl** [comment]
Fixed! Thanks for reporting this!
